name: create backend bucket

on:
    pull_request:
        branches:
            - development

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}  

jobs:
  create_backend_bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5   

      - name: check if s3-bucket exists
        id: check_bucket
        run: |
          BUCKET_NAME="s3-state-bucket-doyin"
          if aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            echo "Bucket exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Bucket does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.5.7

      - name: Create S3 bucket if it does not exist
        working-directory: terraform/bootstrap
        if: env.exists == 'false'
        run: |
            terraform init
            terraform validate
            terraform plan -out=tfplan -var-file=../env/initial-s3.tfvars
            terraform apply -auto-approve tfplan

            echo "Terraform applied successfully."