name: terraform pipeline

on:
    pull_request:
        branches:
        - staging
        - production

env:
    aws_key: ${{ secrets.AWS_ACCESS_KEY }}
    aws_secret: ${{ secrets.AWS_SECRET_KEY }}   

jobs:
    terraform:
        name: Terraform Plan and Apply
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.7

            - name: Terraform Init
              working-directory: terraform
              run: terraform init

            - name: Terraform Validate
              working-directory: terraform
              run: terraform validate

            - name: Terraform Plan
              working-directory: terraform
              run: terraform plan -var-file=env/${{ github.base_ref }}.tfvars

            - name: Terraform Apply
              working-directory: terraform
              if: github.event_name == 'pull_request' && github.event.action == 'opened'
              run: terraform apply -auto-approve -var-file=env/${{ github.base_ref }}.tfvars